name: Deploy Prod

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build


      - name: Copy dist folder contents
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          path: dist



  deploy:
    runs-on: ubuntu-latest
    needs: build # Run after the 'build' job completes
    steps:
      - name: Checkout github-pages branch
        uses: actions/checkout@v4
        with:
          ref: github-pages
          fetch-depth: 0 # Important: fetch entire history for force-push

      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-artifact
          path: dist

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Deploy to github-pages
        run: |
          git rm -rf . # Remove existing files (use with caution!)
          mv dist/* . # Move content from 'dist' to root
          rmdir dist # Remove the 'dist' folder
          git add -A
          git commit -m "Deploy to github-pages"
          git push origin HEAD:github-pages --force # Force-push changes

